# Generated by Django 4.0.5 on 2022-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdata',
            name='quantity',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
