# Generated by Django 4.0.5 on 2022-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0006_fdata_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='rcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal', models.IntegerField()),
            ],
        ),
    ]
