# Generated by Django 4.0.5 on 2022-10-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0007_rcal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rcal',
        ),
    ]
