# Generated by Django 4.0.5 on 2022-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0008_delete_rcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='rcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcal', models.IntegerField()),
            ],
        ),
    ]
