# Generated by Django 4.0.5 on 2022-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0009_rcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcal',
            name='rcal',
            field=models.IntegerField(blank=True),
        ),
    ]
