# Generated by Django 4.0.5 on 2022-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0011_fdata_carbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdata',
            name='carbs',
            field=models.FloatField(),
        ),
    ]
