# Generated by Django 4.0.5 on 2022-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0013_remove_fdata_carbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdata',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
    ]
