# Generated by Django 4.0.5 on 2022-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0017_remove_fdata_carbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdata',
            name='carbs',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
